server:
  port: 9900
spring:
  datasource:
    url: jdbc:mysql://192.168.7.128:3306/snc-music?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: snc-music
    password: HH8HnpZiFRm7CarA
  data:
    redis:
      database: 1
      host: 192.168.7.128
      password: jhkdjhkjdhsIUTYURTU_xtAYK3